### ISSUE TITLE
ESRI Locator Endpoint for AGOL Compatability

### ISSUE THREAD

**Issue by stdavis** [agrc/wri-webapi#16]
With all of these new AGOL apps coming online there has been interest in being able to point them at our geocoder. Currently, I believe that Michael published our Roads_AddressSystem_STREET service to AGOL and that has been what most of the apps are pointing at. This presents a problem since it only works if you input the correct address system. I doesn't work with zip or city (unless the name of the city is the same as the address system). It also doesn't work with ALIAS street names or address points.

It would be great to create an endpoint for our geocoding service that matches the ESRI geolocator endpoint so that it could be used in AGOL.

I order for this to work I would guess that you need to implement the following two endpoints:

http://mapserv.utah.gov/arcgis/sdk/rest/index.html#/Geocode_Service/02ss0000003n000000/
http://mapserv.utah.gov/arcgis/sdk/rest/index.html#/Find_Address_Candidates/02ss00000015000000/

Find_Address_Candidates has a lot of parameters that we may not need.

**Comment by steveoh** [comment]
[duplicate](https://github.com/agrc/api.mapserv.utah.gov/issues/1)

**Comment by stdavis** [comment]
Thanks for setting me straight, @steveoh. However, I'm dissappointed that it took you longer than 60 seconds. ;)

**Comment by steveoh** [comment]
:clock1: not sure why you tossed this in wri. Am I missing something? I'll try to be more responsive in the future.

**Comment by stdavis** [comment]
I just got the wrong repo. I saw "webapi" and pulled the trigger.

On Thu, Mar 31, 2016 at 10:32 AM, steveoh notifications@github.com wrote:

> [image: :clock1:] not sure why you tossed this in wri. Am I missing
> something? I'll try to be more responsive in the future.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/wri-webapi/issues/16#issuecomment-204011029

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@SThomasDavis https://twitter.com/SThomasDavis
