### ISSUE TITLE
create features

### ISSUE THREAD

**Issue by steveoh** [agrc/wri-webapi#2]
`POST` to `/project/{id:int}/feature/create` where `id` is the `projectId`

``` js
category: 'the things from the lu_featuretype'
token: 'gathered from the form'
key: 'gathered from the form'
geometry:  'MULTIPOINT((-122.63 45.51),(-122.56 45.51),(-122.56 45.55))' *
attributes: 'i've yet to work out this object out yet'
```

\* If we use [WKT](https://github.com/arthur-e/Wicket) for the geometry,  I can use sql to test for the feature overlaps and insert the geometry with sql instead of the feature service. It removes some arcgis server complexity/overhead but adds a dependency on Wicket. It is on bower, it is pretty small, and it is not an amd module. Thoughts?

``` js
var wkt = new wkt.Wkt();
var geom = wkt.deconstruct(esriGeometry);
wkt.components = geom.components;
wkt.type = geom.typ;
var wktext = wkt.write();
```

**Comment by steveoh** [comment]
@stdavis what do you think about the geometry here?

**Comment by stdavis** [comment]
I don't mind doing a bit of work on the front end to make the back end cleaner. Doesn't seem like it will be a problem at all to me.

Where did you get your code sample? The [readme](https://github.com/arthur-e/Wicket) says not to use `deconstruct` but to use `fromObject` instead.

**Comment by steveoh** [comment]
I just hacked it up in the console real quick.

**Comment by stdavis** [comment]
Ya, their docs are not very clear.

On Wed, Sep 9, 2015 at 8:21 AM, steveoh notifications@github.com wrote:

> I just hacked it up in the console real quick.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agrc/wri-webapi/issues/2#issuecomment-138924781.

## 

_Scott Davis_
Utah AGRC http://gis.utah.gov/developer/
stdavis@utah.gov
@SThomasDavis https://twitter.com/SThomasDavis

**Comment by steveoh** [comment]
there is also [terraformer](https://github.com/Esri/Terraformer) which could work and is from esri. You would need to go graphic to geojson to wkt.

**Comment by stdavis** [comment]
@steveoh Decided that he wants the geometry as esri JSON now to make it easier for him to send to the SOE for validation checks. Conversion to WKT will be done on the server after validation has passed.
